spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/nogizaka
    username: walk8243
    password: shLG425x
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful

app:
  name: java-study-nogizaka-api
